#!/bin/bash

# Display helpful information
echo ""
echo "🎯 Development Environment Ready!"
echo ""
echo "📋 Available commands:"
echo "  api                    - Start the .NET API"
echo "  frontend               - Start the React frontend"
echo "  test-api               - Run backend tests"
echo "  test-frontend          - Run frontend tests"
echo "  build-all              - Build both backend and frontend"
echo "  fix-permissions        - Fix file permissions if needed"
echo ""
echo "🔧 Dynamic API Provider commands:"
echo "  providers              - View current API providers"
echo "  refresh-providers      - Refresh provider cache"
echo "  mock-config            - View mock configuration service"
echo "  disable-provider <id>  - Disable a provider (e.g., disable-provider filmworld)"
echo "  enable-provider <id>   - Enable a provider (e.g., enable-provider filmworld)"
echo ""
echo "🌐 Default URLs:"
echo "  Frontend: http://localhost:3000"
echo "  API: http://localhost:5091"
echo "  Swagger: http://localhost:5091/swagger"
echo "  Mock Config: http://localhost:5091/api/MockConfiguration/api-providers"
echo "  Redis: localhost:6379"
echo ""
echo "💡 Tips:"
echo "  - Run 'source ~/.bashrc' to load the new aliases in your current session"
echo "  - Use 'providers' to see current API provider configurations"
echo "  - Use 'disable-provider cinemaworld' to disable a provider for testing"
echo "  - Check the dynamic API provider documentation in MoviePriceComparison/README-DYNAMIC-API-PROVIDERS.md"
echo "  - Use 'Ctrl+Shift+\`' to open a new terminal"
echo "  - Run both 'api' and 'frontend' in separate terminals for full development"
echo "  - Check the README.md for detailed setup instructions"
echo ""
